import { PLAYER_BASE } from '../data/balance.js';
import { CAMPAIGN_START_MISSION_INDEX } from '../data/missions.js';
import { createDefaultShopPurchases, createDefaultUpgradeLevels } from '../progression/UpgradeStateShared.js';

/**
 * Responsibility:
 * - Creates a fresh campaign runtime state.
 *
 * Rules:
 * - This file owns the shape of the state tree.
 * - Systems may mutate values, but they must not change the schema at runtime.
 * - Any cross-system state that affects feel must remain here explicitly.
 * - New cross-system timers must be declared here first so later refactors do not create hidden state in random modules.
 * - `mode: "paused"` is a real runtime state. Gameplay systems must treat it as fully frozen.
 *   Do not add hidden pause booleans in other modules or the game will desync when pointer-lock is released.
 * - `mode: "gameoverSequence"` is reserved for the player-down crash animation before the final game-over screen freeze.
 * - Mission retry restores from a mission-start checkpoint stored here. Do not hide retry snapshots in UI code or ad-hoc locals.
 */
export function createInitialState() {
  return {
    mode: 'title',
    elapsed: 0,
    score: 0,
    crystals: 0,
    missionIndex: 0,
    missionIntroTimer: 0,
    damageFlash: 0,
    ui: {
      notice: { text: '', timer: 0, duration: 0, fadeInDuration: 0, fadeOutDuration: 0, justShown: false },
      intervalTransition: {
        armed: false,
        active: false,
        duration: 0,
        startedAtMissionIndex: -1,
      },
      clearIntelUnlockPopup: {
        armed: false,
        timer: 0,
        visible: false,
      },
      damageIndicators: [],
      damageIndicatorCounter: 0,
    },
    player: {
      x: 0,
      y: PLAYER_BASE.hoverHeight,
      z: 0,
      yaw: 0,
      pitch: -0.16,
      vx: 0,
      vz: 0,
      recoil: 0,
      bob: 0,
      health: PLAYER_BASE.maxHealth,
      maxHealth: PLAYER_BASE.maxHealth,
      invulnTimer: 0,
      primaryCooldown: 0,
      plasmaCooldown: 0,
      shooting: false,
      weaponHeat: 0,
      crashTimer: 0,
      crashDuration: 0,
      crashImpactTimer: 0,
      crashFallVelocity: 0,
      crashDriftX: 0,
      crashDriftZ: 0,
      crashSpinX: 0,
      crashSpinY: 0,
      crashSpinZ: 0,
      crashImpacted: false,
    },
    progression: {
      wave: 0,
      waveTarget: 0,
      waveBaseTarget: 0,
      waveSpawned: 0,
      waveAliveAtStart: 0,
      spawnTimer: 0,
      waveBurstPlan: [],
      waveBurstIndex: 0,
      interWaveTimer: 0,
      bossPreAlertPending: false,
      bossAlertCueTimer: 0,
      bossAlertCueDuration: 0,
      clearSequenceTimer: 0,
      clearSequenceDuration: 0,
      clearAnnouncementDelay: 1,
      clearResultDelay: 3,
      clearAnnouncementPlayed: false,
      clearResultReached: false,
      clearBgmTrackId: null,
      clearBgmCueDelay: 0,
      clearBgmPlayed: false,
      suppressMissionClearSfx: false,
      missionStatus: 'idle',
      bossActive: false,
      bossDefeated: false,
      pausedStatus: 'idle',
      missionNoDownEligible: true,
      missionNoDownBonus: 0,
      noDownBlockedMissions: {},
      upgrades: createDefaultUpgradeLevels(),
      shopPurchases: createDefaultShopPurchases(),
      missionCheckpoint: {
        missionIndex: 0,
        score: 0,
        crystals: 0,
      },
      intervalMissionIndex: 0,
      intervalContext: 'advance',
      missionTimer: 0,
      missionTimerActive: false,
      missionTargetTime: 0,
      campaignClearTime: 0,
      missionTimeBonus: 0,
      missionFinalCrystalBonus: 0,
      missionFailCrystalAward: 0,
      missionFailCrystalBanked: 0,
      lastMissionSummary: null,
      medalCollection: {},
      clearResultForcedVisibleCount: 0,
      clearIntelUnlockPending: false,
      finalClearCinematic: {
        active: false,
        started: false,
        timer: 0,
        duration: 0,
        cameraBlendDuration: 0,
        flightDelay: 0,
        straightDuration: 0,
        curveDuration: 0,
        shipYaw: 0,
        cameraPosition: { x: 0, y: 0, z: 0 },
        lookTarget: { x: 0, y: 0, z: 0 },
        shipStart: { x: 0, y: 0, z: 0 },
        shipMid: { x: 0, y: 0, z: 0 },
        shipCurveControl: { x: 0, y: 0, z: 0 },
        shipEnd: { x: 0, y: 0, z: 0 },
        sparkleEmitTimer: 0,
      },
      tutorial: {
        active: false,
        totalSteps: 0,
        stepIndex: -1,
        stepTitle: '',
        objective: '',
        progressText: '',
        enemyIds: [],
        moveDistance: 0,
        lookTravel: 0,
        stepElapsed: 0,
        startCrystals: 0,
        requiredCrystals: 0,
        primaryUsed: false,
        plasmaUsed: false,
        lastX: 0,
        lastZ: 0,
        lastYaw: 0,
        lastPitch: 0,
      },
      debug: {
        enabled: false,
        invincible: false,
        bossMode: false,
        titleStartMissionIndex: CAMPAIGN_START_MISSION_INDEX,
      },
    },
  };
}
